site_name: Panacea
site_url: https://docs.anote.ai
use_directory_urls: false
# repo_url: https://github.com/nv78/Anote
site_description: "Collaborative Multi Agentic AI Framework."
# site_author: "Natan Vidra"


# Navigation structure
nav:
  - Introduction: "1_introduction.md"
  - System Architecture:
      - Overview: "2_system_architecture_overview.md"
      - Key Components: "2_key_components.md"
  - Agent Design:
      - Agent Types: "3_agent_types.md"
      - Agent Environment: "3_agent_environment.md"
  - Workflow Management:
      - Task Execution: "4_task_execution.md"
      - Orchestration: "4_orchestration.md"
  - Communication Framework: "5_communication_framework.md"
  - User Interface:
      - Chat-Based Interface: "6_chat_based_interface.md"
      - Agent Creation: "6_agent_creation.md"
  - API and Enterprise Features:
      - Developer API: "7_developer_api.md"
      - Enterprise Solutions: "7_enterprise_solutions.md"
  - Use Cases:
      - Autonomous AI Coding Agent: "11_autonomous_ai_coding_agent.md"
      - Autonomous AI Sales Agent: "11_autonomous_ai_sales_agent.md"
      - Autonomous AI Job Seeker Agent: "11_autonomous_ai_job_seeker_agent.md"
      - Autonomous Query Agent: "11_autonomous_query_agent.md"
  - Deployment:
      - Local Deployment: "8_local_deployment.md"
      - Private Deployment: "8_private_deployment.md"
  - Logging and Monitoring: "9_logging_and_monitoring.md"
  - Glossary: "10_glossary.md"


extra:
  homepage: https://anote.ai
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/anote-ai/
    - icon: fontawesome/brands/medium
      link: https://anote-ai.medium.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
  favicon: images/logo.png
  logo: images/logo.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
  - swagger-ui-tag:
      syntaxHighlightTheme: monokai
      tryItOutEnabled: false
      supportedSubmitMethods: []